apiVersion: 1

prune: false

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    uid: grafana_loki
    url: http://loki.railway.internal:3100
    jsonData:
      maxLines: 1000
      timeout: 60
    isDefault: false
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    uid: grafana_tempo
    url: http://tempo.railway.internal:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'grafana_loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags: ['service_name', 'job', 'instance']
        filterByTraceID: true
      tracesToMetrics:
        datasourceUid: 'grafana_prometheus'
      serviceMap:
        datasourceUid: 'grafana_prometheus'
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: 'grafana_loki'
    isDefault: false
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: grafana_prometheus
    url: http://prometheus.railway.internal:9090
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: 'grafana_tempo'
      timeInterval: 30s
    isDefault: true
    editable: true
